### ISSUE TITLE
Nom du module dans go.mod

### ISSUE THREAD

**Issue by louisroyer** [shynuu/trunks#2]
Salut,
j’ai voulu essayer de build ton programme avec docker mais soit je m’y prend mal (je n’utilise pas les même commandes que dans le README, mais ça me semblait plus propre pour ce cas-ci), soit il faudrait modifier la ligne
https://github.com/shynuu/trunks/blob/42ed31f888aa37da0b007a55e70e9ea83edb75e7/go.mod#L1
en `module github.com/shynuu/trunks`.
En effet, lorsque je fais `go get -d github.com/shynuu/trunks`, j’obtiens :
```
# cd .; git clone -- https://github.com/shynuu/go-trunks /go/src/github.com/shynuu/go-trunks                                                          
Cloning into '/go/src/github.com/shynuu/go-trunks'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled                                                                    
package github.com/shynuu/go-trunks/trunks: exit status 128
```

Voici la manière dont je voudrais faire fonctionner mon dockerfile :
```DockerFile
FROM golang:1.14 AS builder

WORKDIR /go/src/github.com/shynuu/trunks
RUN go get -d github.com/shynuu/trunks
RUN go install github.com/shynuu/trunks

FROM debian:buster-slim
COPY --from=builder /go/bin/trunks /usr/local/sbin/trunks
ENTRYPOINT trunks # todo: ajouter la config 
```
Voici la manière dont je parviens à le compiler pour l’instant :
```DockerFile
FROM golang:1.14 AS builder

WORKDIR /go/src/github.com/shynuu/go-trunks
RUN git clone -- https://github.com/shynuu/trunks /go/src/github.com/shynuu/go-trunks                                                                 
RUN go get -d .
RUN go install github.com/shynuu/go-trunks

FROM debian:buster-slim
COPY --from=builder /go/bin/go-trunks /usr/local/sbin/trunks
ENTRYPOINT trunks
```

**Comment by shynuu** [comment]
Salut Louis,

Le problème devrait être résolu avec le fix name. 

Essaie de nouveau en faisant

```bash
go clean -modcache
go get github.com/shynuu/trunks
go install github.com/shynuu/trunks
```

Ta méthode devrait ensuite fonctionner, tiens moi au courant.

Youssouf

**Comment by louisroyer** [comment]
oui, ça fonctionne avec ma méthode maintenant (en pensant à bien mettre le changement de workdir *après* le go get).
